name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # http: ^1.2.2
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  news_api_flutter_package: ^1.2.0
  # flutter_webview_plugin: ^0.4.0
  webview_flutter: ^4.10.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  shared_preferences: ^2.3.4
  # get_storage: ^2.1.1
  share_plus: ^10.1.3
  intl: ^0.20.1
  smooth_page_indicator: ^1.2.0+3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/kota.png"
